backend-common: [backend-common/**]
bitwarden: [bitwarden/**]
clickhouse-keeper: [clickhouse-keeper/**]
clickhouse: [clickhouse/**]
fluentd: [fluentd/**]
github-actions-runner: [github-actions-runner/**]
ipsec: [ipsec/**]
keydb: [keydb/**]
link-common: [link-common/**]
mongodb-backup: [mongodb-backup/**]
mongosqld: [mongosqld/**]
mongosync: [mongosync/**]
openvpn: [openvpn/**]
overprovisioner: [overprovisioner/**]
pgbouncer: [pgbouncer/**]
plausible: [plausible/**]
postgresql-single: [postgresql-single/**]
prometheus-rules: [prometheus-rules/**]
rbac-common: [rbac-common/**]
registry-mirrors: [registry-mirrors/**]
service-common: [service-common/**]
skipper: [skipper/**]
system-upgrade-controller: [system-upgrade-controller/**]
tabix: [tabix/**]
tailscale: [tailscale/**]
teamcity: [teamcity/**]
