{{- if .Values.envSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "talos-backup.fullname" . }}-envs
  labels:
    {{- include "talos-backup.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $name, $value := .Values.envSecrets }}
  {{ $name }}: {{ tpl $value $ | b64enc | quote }}
{{- end }}
{{- end }}
