{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "talos-backup.serviceAccountName" . }}
  labels:
    {{- include "talos-backup.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: {{ include "talos-backup.serviceAccountName" . }}-secrets
  labels:
    {{- include "talos-backup.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  roles:
    - os:etcd:backup
