apiVersion: v2
name: system-upgrade-controller
description: System Upgrade Controller for Talos
type: application
home: https://github.com/sergelogvinov/helm-charts
sources:
  - https://github.com/sergelogvinov/helm-charts/tree/main/charts/system-upgrade-contoller
keywords:
  - system-upgrade-controller
maintainers:
  - name: sergelogvinov
    url: https://github.com/sergelogvinov

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# https://github.com/rancher/system-upgrade-controller
appVersion: "v0.14.2"
