ingressClass: skipper
ingressClassResource:
  enabled: true

# hostNetwork: true
# hostPort:
#   ports:
#     http: 8080
#     https: 8443

priorityClassName: system-cluster-critical

useDaemonSet: true
terminationGracePeriodSeconds: 120
