apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "registry-mirrors.fullname" . }}
  labels:
    {{- include "registry-mirrors.labels" . | nindent 4 }}
data:
  config.json: |-
    {
      "distSpecVersion": "1.1.0",
      "storage": {
        "rootDirectory": "/var/lib/registry",
        "commit": true,
        "gc": true,
        "gcDelay": "1h",
        "gcInterval": "12h"
      },
      "http": {
        "address": "0.0.0.0", "port": "8080"
      },
      "log": { "level": "warn" },
      "extensions": {
        "metrics": {
          "enable": true,
          "prometheus": {
            "path": "/metrics"
          }
        },
        "sync": {
          "enable": true,
          "credentialsFile": "/etc/credentials/credentials.json",
          "registries": [
            {{- range $inx, $val := .Values.mirrors }}{{- if ne $val.host "docker.io" }}
            {
              "urls": ["https://{{ $val.host }}"],
              "tlsVerify": true,
              "onDemand": true,
              "maxRetries": 3,
              "retryDelay": "15m",
              "onlySigned": false,
              "content": [
                {
                  "prefix": "**",
                  "destination": "/{{ $val.host | replace "." "-" }}"
                }
              ]
            },
            {{- end }}{{- end }}
            {
              "urls": ["https://index.docker.io"],
              "tlsVerify": true,
              "onDemand": true,
              "maxRetries": 3,
              "retryDelay": "15m",
              "onlySigned": false,
              "content": [
                {
                  "prefix": "library/**",
                  "destination": "/docker-io"
                },
                {
                  "prefix": "**",
                  "destination": "/docker-io"
                },
                {
                  "prefix": "library/**"
                },
                {
                  "prefix": "moby/**"
                },
                {
                  "prefix": "docker/**"
                },
                {
                  "prefix": "multiarch/**"
                }
              ]
            }
          ]
        }
      }
    }
