apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "registry-mirrors.fullname" . }}
  labels:
    {{- include "registry-mirrors.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
  selector:
    matchLabels:
      {{- include "registry-mirrors.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/mirrors: {{ toJson .Values.mirrors | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "registry-mirrors.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "registry-mirrors.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "registry-mirrors.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /v2/
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: cache
              mountPath: /var/lib/registry
            - name: config
              mountPath: /etc/zot
            - name: credentials
              mountPath: /etc/credentials
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "registry-mirrors.fullname" . }}
        - name: credentials
          secret:
            secretName:  {{ include "registry-mirrors.fullname" . }}
            defaultMode: 256
        {{- if .Values.persistence.storageClass }}
        - name: cache
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  {{- include "registry-mirrors.labels" . | nindent 22 }}
              {{- with .Values.persistence.annotations }}
                annotations:
                {{- range $key, $value := . }}
                  {{ $key }}: {{ $value }}
                {{- end }}
              {{- end }}
              spec:
                accessModes:
                {{- range .Values.persistence.accessModes }}
                  - {{ . | quote }}
                {{- end }}
                resources:
                  requests:
                    storage: {{ .Values.persistence.size | quote }}
              {{- if .Values.persistence.storageClass }}
              {{- if (eq "-" .Values.persistence.storageClass) }}
                storageClassName: ""
              {{- else }}
                storageClassName: "{{ .Values.persistence.storageClass }}"
              {{- end }}
              {{- end }}
        {{- else }}
        - name: cache
          emptyDir: {}
        {{- end }}
