{{- $pwd := include "registry-mirrors.password" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry-mirrors.fullname" . }}
  labels:
    {{- include "registry-mirrors.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ "mirror " | b64enc | quote }}
  password: {{ $pwd | b64enc | quote }}
  htpasswd: {{ htpasswd "mirror" $pwd | b64enc | quote }}
  credentials.json: {{ include "registry-mirrors.credentialsFile" . | fromYaml | toJson | b64enc | quote }}
