{{- if .Values.envs.envs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitwarden.fullname" . }}
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $name, $value := .Values.envs }}
  {{ $name }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
