name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 9 * * 1-5'

jobs:
  renovate:
    name: "Renovate"
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: write
      issues: write
      pull-requests: write
      security-events: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Helm docs
        uses: gabe565/setup-helm-docs-action@v1
        with:
          version: v1.11.3

      - name: Renovate
        uses: renovatebot/github-action@v41.0.3
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: "debug"
